language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
env:
  global:
  - secure: DSgWbsLSzMIJjK08Eb9uaBROtT9qwrO1ZInXfUbqFSan3GWGNB1tL5veDD9dGbxK4vzbu8050VD0YQD8OlEDVQ7f7z+ppzY/+WC+nsdmzqmISy9pTn663oELhlK3Pl86rf6dmVaQnCWHNpWdQHQO5y1q45rz9C+He5OHGVFqS0TzKvcO7PndGK292G/jybgdGA+wlvbAZzhHj39WA6U6AUw49HTvAR4s2CT+bIbfdNm7zTG9bPnYGczx7+5jzfaAxDJ7LOlbH4PY0ra1tonl7P9sRqtFDO9XQa9yJ3nmO2nzBnZJH6nviCSv1cam+gGaeZ2yq+8W63TPBc3CsCPLpJETwwi2wKJq2Fo/I5t7CW6AxR9IvRD7s0oHDhMevrlcLT5jXAUHBUAANUs7MupvUAGjOAqXCfI4Jg6mor9q4wPJPsT4s+sVI8/sfG2OHF7nbFL8Da8pUQwI38qOpcE1qAJzRUNfUu3X0Mu/fcffz6rN23U3+KJsPr2i6NwGKivIveZMkb9nDI52/6Yx9w6WBsK9G9ToMrKcMzmzzQ9i4CtovmiFEj2FZtrgyntaO8tBRnSonQJ1ElvjwY3zwk0vKDOQveMxFK1x/Jgpg7oNVsgEssdLbKd3VaV8Ka4o++RjQYrQj0lQ/EeuVm+ez4CaDdmmihMrZNSIYiL+MsQcvy4=
  - secure: i0vv/fh2iK5U6pG6oW1ugM1x72a1zIXlAZCrFp0oX/sjYptN6QoidTLWmkraLPgWJ46ImTzJJ4PTVTk/k0025h3bSvZamvCElyF2YelyWT+pbYhslM3mtoARSsnH5V3/aqjyvrEqIhfT8ZFwnKojRDslqdQWj4Awn+US8HlQYhob3sPLhgRGhELV+Q3Fl3D9U7iLWkfJQl9yNJQaVOYBTuYW57r/kpiJq5clt3Y10pbDygFv++P2C12v8bdCRi7ZbnGbHTdLfl0Igvufb6tryjxnuKXOBc0lBzfXto5fZgYud/H3FJ0PrDkJI4M0U1oY2fCbuG0YgesKCworMUwUJPKgwkAbmfjyIcD1ZxZwi8/qOrPX4mm4RqSErWkqpNYV6U6cUPmA7j3ReKKmLecAK8+Nke6Vvqhz+w4/ZZf/1taR8dNvIPNGFGwfMiS9mqPI45MPC4VrROc0smo4MsV6ghCSR9Xz0jaul2jcYd3ghasUFq4azQc9RSXIMaXIJWKaCui/To0XTut253nhLuLZEzCiOSH9Ov3ELquoUSgcg+sch1Ib3Sw4cA9SspnG3K5VNXUzgcFV2OTASnq5TJ5Rsm4eUes1Ozw1vBMq+ZkNbV/zYg0jD6BwUmNGDLA/RhAFCKCxm+tiE/pPJBmksKv3ZIAu5xlG9usgL3eqP9eHolY=
after_success:
# - "./deploy.sh"
